const usernames = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const emails = [
  'mail@mail.com',
  'nomail@gmail.com',
  'mail@gmail.com',
  'hotmail@hotmail.com',
  'live@live.com',
  'test@test.com',
  'Mtest@admin.com',
  'admin@admin.com',
  'carlos@mail.com',
  'peter@mail.com',
  'work@mail.com',
  'boss@mail.com',
  'press@mail.com',
  'bart@mail.com',
  'Ziyaa@mail.com',
  'Zohai@mail.com',
  'Zouba@mail.com',
  'Zubai@mail.com',
  'Zubay@mail.com',
  'Zurie@mail.com',
  'Xande@mail.com',
  'Jared@mail.com',
  'Court@mail.com',
  'Gilli@mail.com',
  'Clark@mail.com',
  'Jared@mail.com',
  'Grace@mail.com',
];

const thoughts = [
  'Going to the beach',
  'Waiting for holidays...',
  'In classes...',
  'Waiting for COVID to dissapear',
  'All I want is a brand new car',
  'I cannot wait to go to Australia',
  'USA is the best country in the world',
  'How do I tell my gf I want to break up?',
  'Lorem10',
  'I like robots',
  'I hate birds',
  'I cannot stand my boss',
]

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random name
const getRandomUsername = () =>
  `${getRandomArrItem(usernames)}`;

// Get a random email
const getRandomEmail = () =>
  `${getRandomArrItem(emails)}`;

// Get a random thought
const getRandomThought = () =>
  `${getRandomArrItem(thoughts)}`;

// Export the functions for use in seed.js
module.exports = { usernames, emails, getRandomThought };
